# Generated by Django 6.0 on 2025-12-18 11:34

import django.db.models.deletion
import voucher.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendor", "0002_remove_vendorprofile_admin_approved_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        default=voucher.models.generate_voucher_code,
                        max_length=14,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PHARMACY", "Pharmacy"),
                            ("SCHOOL", "School"),
                            ("HARDWARE", "Hardware Store"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Redeemable by vendors in this category",
                        max_length=50,
                    ),
                ),
                (
                    "initial_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "remaining_balance",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_PAYMENT", "Pending Payment"),
                            ("ACTIVE", "Active"),
                            ("LOCKED", "Locked"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING_PAYMENT",
                        max_length=20,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True, default=voucher.models.default_expiry, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoucherRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "redeemed_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher_redemptions",
                        to="vendor.vendorprofile",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="voucher.voucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voucher Redemption",
                "verbose_name_plural": "Voucher Redemptions",
            },
        ),
    ]
