# Generated by Django 6.0 on 2025-12-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucherredemption",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
