# Generated by Django 6.0 on 2025-12-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher", "0002_voucherredemption_is_confirmed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voucherredemption",
            name="is_confirmed",
        ),
        migrations.AddField(
            model_name="voucherredemption",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("REDEEMED", "Redeemed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
