# Generated by Django 6.0 on 2025-12-21 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voucher", "0003_remove_voucherredemption_is_confirmed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voucherredemption",
            old_name="status",
            new_name="redemption_status",
        ),
    ]
