# Generated by Django 6.0 on 2025-12-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher", "0005_voucher_escrow_balance_alter_voucher_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="category",
            field=models.CharField(
                choices=[
                    ("PHARMACY", "Pharmacy"),
                    ("SCHOOL", "School"),
                    ("HARDWARE", "Hardware Store"),
                    ("FOOD AND GROCERIES", "Food and Groceries"),
                    ("OTHER", "Other"),
                ],
                help_text="Redeemable by vendors in this category",
                max_length=50,
            ),
        ),
    ]
