# Generated by Django 6.0 on 2025-12-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number of the user (Ghanaian format).",
                max_length=15,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture of the user.",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
    ]
